/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'service-categories': ServiceCategory;
    services: Service;
    'service-areas': ServiceArea;
    'team-members': TeamMember;
    reviews: Review;
    faqs: Faq;
    'gallery-items': GalleryItem;
    'quote-requests': QuoteRequest;
    'vehicle-makes': VehicleMake;
    'vehicle-models': VehicleModel;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'service-categories': ServiceCategoriesSelect<false> | ServiceCategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-areas': ServiceAreasSelect<false> | ServiceAreasSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    'quote-requests': QuoteRequestsSelect<false> | QuoteRequestsSelect<true>;
    'vehicle-makes': VehicleMakesSelect<false> | VehicleMakesSelect<true>;
    'vehicle-models': VehicleModelsSelect<false> | VehicleModelsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'sections-settings': SectionsSetting;
    'hero-settings': HeroSetting;
    'site-settings': SiteSetting;
    'homepage-layout': HomepageLayout;
    navigation: Navigation;
    'whatsapp-settings': WhatsappSetting;
  };
  globalsSelect: {
    'sections-settings': SectionsSettingsSelect<false> | SectionsSettingsSelect<true>;
    'hero-settings': HeroSettingsSelect<false> | HeroSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'homepage-layout': HomepageLayoutSelect<false> | HomepageLayoutSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'whatsapp-settings': WhatsappSettingsSelect<false> | WhatsappSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage admin accounts that can log into this dashboard
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload and manage images, logos, certificates & documents
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility (e.g. "Front door deadbolt installation")
   */
  alt: string;
  /**
   * Optional caption shown below the image
   */
  caption?: string | null;
  /**
   * Which section this media belongs to (auto-detected on upload)
   */
  mediaCategory?:
    | ('uncategorized' | 'gallery' | 'services' | 'team' | 'hero' | 'branding' | 'vehicles' | 'quotes')
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Residential, Commercial & Automotive — the 3 main service groups
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories".
 */
export interface ServiceCategory {
  id: number;
  /**
   * Category name shown on the website
   */
  name: string;
  /**
   * Auto-generated from name — used in URLs
   */
  slug: string;
  /**
   * Short label for navigation tabs
   */
  label?: string | null;
  /**
   * Accent color (e.g. #3B82F6)
   */
  color?: string | null;
  /**
   * Category page headline
   */
  headline?: string | null;
  /**
   * Brief description shown under the category heading
   */
  description?: string | null;
  /**
   * Banner image for this category
   */
  heroImage?: (number | null) | Media;
  /**
   * Custom page title for search engines
   */
  seoTitle?: string | null;
  /**
   * Meta description for search results
   */
  seoDescription?: string | null;
  /**
   * Uncheck to hide this category from the website
   */
  isActive?: boolean | null;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * All 29 locksmith services — edit pricing, descriptions, images & more
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Service name shown on the website
   */
  title: string;
  /**
   * Auto-generated — used in URLs
   */
  slug: string;
  /**
   * Which category does this service belong to?
   */
  category: number | ServiceCategory;
  /**
   * One-liner shown on the service card (keep it under 120 characters)
   */
  shortDescription?: string | null;
  /**
   * Pick an icon
   */
  icon?: string | null;
  /**
   * Call-to-action button text
   */
  ctaText?: string | null;
  /**
   * Main image shown when a customer clicks on this service
   */
  heroImage?: (number | null) | Media;
  /**
   * Full description — shown in the service detail popup
   */
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Key selling points — shown as a checklist
   */
  benefits?:
    | {
        /**
         * e.g. "No damage to locks or doors"
         */
        benefit: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Custom page title for search engines
   */
  seoTitle?: string | null;
  /**
   * Meta description for search results (150-160 chars ideal)
   */
  seoDescription?: string | null;
  /**
   * Uncheck to hide this service from the website
   */
  isActive?: boolean | null;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas".
 */
export interface ServiceArea {
  id: number;
  cityName: string;
  slug: string;
  state?: string | null;
  lat: number;
  lng: number;
  radiusMiles?: number | null;
  responseTime?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Uncheck to hide from website
   */
  isActive?: boolean | null;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  experience?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  specialties?:
    | {
        specialty?: string | null;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        name?: string | null;
        file?: (number | null) | Media;
        fileType?: ('image' | 'pdf') | null;
        expiryDate?: string | null;
        isVerified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck to hide from website
   */
  isActive?: boolean | null;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  customerName: string;
  starRating: number;
  reviewText: string;
  reviewDate?: string | null;
  source?: ('website' | 'google' | 'yelp' | 'manual') | null;
  /**
   * Approve this review
   */
  isApproved?: boolean | null;
  /**
   * Uncheck to hide from website
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently asked questions — shown on the homepage FAQ section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * The question customers ask
   */
  question: string;
  /**
   * Your answer — keep it clear and helpful
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Group this FAQ under a topic
   */
  category?: ('general' | 'pricing' | 'services' | 'emergency') | null;
  /**
   * Uncheck to hide from website
   */
  isActive?: boolean | null;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Before & after project photos. Each item has its own unique before/after images.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  /**
   * Display title (e.g. "Deadbolt Replacement")
   */
  title: string;
  /**
   * Main service category
   */
  category: 'Residential' | 'Commercial' | 'Automotive';
  /**
   * Service name (e.g. "Deadbolt Replacement", "Smart Lock Installation")
   */
  subcategory?: string | null;
  /**
   * 📷 BEFORE photo — upload a unique image for this item
   */
  beforeImage?: (number | null) | Media;
  /**
   * 📷 AFTER photo — upload a unique image for this item
   */
  afterImage?: (number | null) | Media;
  /**
   * Brief description of the work done
   */
  description?: string | null;
  /**
   * Link to the related service (optional)
   */
  service?: (number | null) | Service;
  /**
   * Uncheck to hide from gallery
   */
  isActive?: boolean | null;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Incoming quote requests submitted from the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests".
 */
export interface QuoteRequest {
  id: number;
  /**
   * Update this as you work through the lead
   */
  status: 'new' | 'contacted' | 'quoted' | 'won' | 'lost';
  /**
   * Submitted by customer
   */
  name: string;
  /**
   * Submitted by customer
   */
  phone: string;
  /**
   * Submitted by customer (optional)
   */
  email?: string | null;
  /**
   * Service category selected by customer
   */
  serviceType?: ('residential' | 'commercial' | 'automotive') | null;
  /**
   * Specific service (if selected)
   */
  service?: (number | null) | Service;
  /**
   * Issue description provided by the customer
   */
  body?: string | null;
  /**
   * Address or area entered by customer
   */
  location?: string | null;
  /**
   * GPS latitude (auto-captured)
   */
  lat?: number | null;
  /**
   * GPS longitude (auto-captured)
   */
  lng?: number | null;
  /**
   * Photo uploaded by the customer (e.g. lock, key, vehicle)
   */
  photo?: (number | null) | Media;
  /**
   * Internal notes — not visible to the customer
   */
  adminNotes?: string | null;
  honeypot?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Car brands your locksmith business supports. Add a logo and models for each make.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-makes".
 */
export interface VehicleMake {
  id: number;
  /**
   * Brand name (e.g. Chevrolet, Ford, Toyota)
   */
  name: string;
  /**
   * Upload a logo image (optional — you can use a URL instead)
   */
  logo?: (number | null) | Media;
  /**
   * Or paste a logo image URL here (e.g. https://www.carlogos.org/car-logos/ford-logo.png)
   */
  logoUrl?: string | null;
  /**
   * Add all car models for this brand
   */
  models?:
    | {
        /**
         * Model name (e.g. F-150, Silverado, Camry)
         */
        name: string;
        /**
         * List of locksmith services available for this model
         */
        supportedServices?:
          | {
              /**
               * Service name (e.g. Car Lockout Services, Car Key Replacement)
               */
              service: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Uncheck to hide this model from the website
         */
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck to hide this brand from the website
   */
  isActive?: boolean | null;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-models".
 */
export interface VehicleModel {
  id: number;
  name: string;
  make: number | VehicleMake;
  supportedServices?: (number | Service)[] | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'service-categories';
        value: number | ServiceCategory;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-areas';
        value: number | ServiceArea;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'quote-requests';
        value: number | QuoteRequest;
      } | null)
    | ({
        relationTo: 'vehicle-makes';
        value: number | VehicleMake;
      } | null)
    | ({
        relationTo: 'vehicle-models';
        value: number | VehicleModel;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  mediaCategory?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories_select".
 */
export interface ServiceCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  label?: T;
  color?: T;
  headline?: T;
  description?: T;
  heroImage?: T;
  seoTitle?: T;
  seoDescription?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  icon?: T;
  ctaText?: T;
  heroImage?: T;
  longDescription?: T;
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas_select".
 */
export interface ServiceAreasSelect<T extends boolean = true> {
  cityName?: T;
  slug?: T;
  state?: T;
  lat?: T;
  lng?: T;
  radiusMiles?: T;
  responseTime?: T;
  seoTitle?: T;
  seoDescription?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  experience?: T;
  bio?: T;
  photo?: T;
  specialties?:
    | T
    | {
        specialty?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        file?: T;
        fileType?: T;
        expiryDate?: T;
        isVerified?: T;
        id?: T;
      };
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  customerName?: T;
  starRating?: T;
  reviewText?: T;
  reviewDate?: T;
  source?: T;
  isApproved?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  subcategory?: T;
  beforeImage?: T;
  afterImage?: T;
  description?: T;
  service?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests_select".
 */
export interface QuoteRequestsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  phone?: T;
  email?: T;
  serviceType?: T;
  service?: T;
  body?: T;
  location?: T;
  lat?: T;
  lng?: T;
  photo?: T;
  adminNotes?: T;
  honeypot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-makes_select".
 */
export interface VehicleMakesSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoUrl?: T;
  models?:
    | T
    | {
        name?: T;
        supportedServices?:
          | T
          | {
              service?: T;
              id?: T;
            };
        isActive?: T;
        id?: T;
      };
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-models_select".
 */
export interface VehicleModelsSelect<T extends boolean = true> {
  name?: T;
  make?: T;
  supportedServices?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections-settings".
 */
export interface SectionsSetting {
  id: number;
  _sectionSelector?: string | null;
  services?: {
    heading?: string | null;
    /**
     * Edit the services heading.
     */
    richHeading?: string | null;
    headingAccent?: string | null;
    /**
     * Format the accented word in the heading.
     */
    richAccent?: string | null;
    description?: string | null;
    /**
     * Edit the services description.
     */
    richDescription?: string | null;
  };
  residential?: {
    label?: string | null;
    description?: string | null;
    color?: string | null;
    icon?: string | null;
  };
  commercial?: {
    label?: string | null;
    description?: string | null;
    color?: string | null;
    icon?: string | null;
  };
  automotive?: {
    label?: string | null;
    description?: string | null;
    color?: string | null;
    icon?: string | null;
  };
  reviews?: {
    heading?: string | null;
    /**
     * Edit the section heading with formatting, colors, and fonts.
     */
    richHeading?: string | null;
    subheading?: string | null;
    /**
     * Edit the section subheading with formatting, colors, and fonts.
     */
    richSubheading?: string | null;
    draftData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    publishedData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    status?: ('draft' | 'published') | null;
  };
  gallery?: {
    heading?: string | null;
    /**
     * Edit the section heading with formatting, colors, and fonts.
     */
    richHeading?: string | null;
    subheading?: string | null;
    /**
     * Edit the section subheading with formatting, colors, and fonts.
     */
    richSubheading?: string | null;
    draftData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    publishedData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    status?: ('draft' | 'published') | null;
  };
  quote?: {
    heading?: string | null;
    /**
     * Edit the section heading with formatting, colors, and fonts.
     */
    richHeading?: string | null;
    subheading?: string | null;
    /**
     * Edit the section subheading with formatting, colors, and fonts.
     */
    richSubheading?: string | null;
    draftData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    publishedData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    status?: ('draft' | 'published') | null;
  };
  vehicleVerifier?: {
    heading?: string | null;
    /**
     * Edit the section heading with formatting, colors, and fonts.
     */
    richHeading?: string | null;
    subheading?: string | null;
    /**
     * Edit the section subheading with formatting, colors, and fonts.
     */
    richSubheading?: string | null;
    draftData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    publishedData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    status?: ('draft' | 'published') | null;
  };
  team?: {
    heading?: string | null;
    /**
     * Edit the section heading with formatting, colors, and fonts.
     */
    richHeading?: string | null;
    subheading?: string | null;
    /**
     * Edit the section subheading with formatting, colors, and fonts.
     */
    richSubheading?: string | null;
    draftData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    publishedData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    status?: ('draft' | 'published') | null;
  };
  serviceArea?: {
    heading?: string | null;
    /**
     * Edit the section heading with formatting, colors, and fonts.
     */
    richHeading?: string | null;
    subheading?: string | null;
    /**
     * Edit the section subheading with formatting, colors, and fonts.
     */
    richSubheading?: string | null;
    draftData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    publishedData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    status?: ('draft' | 'published') | null;
  };
  faq?: {
    heading?: string | null;
    /**
     * Edit the section heading with formatting, colors, and fonts.
     */
    richHeading?: string | null;
    subheading?: string | null;
    /**
     * Edit the section subheading with formatting, colors, and fonts.
     */
    richSubheading?: string | null;
    draftData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    publishedData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    status?: ('draft' | 'published') | null;
  };
  contact?: {
    heading?: string | null;
    /**
     * Edit the section heading with formatting, colors, and fonts.
     */
    richHeading?: string | null;
    subheading?: string | null;
    /**
     * Edit the section subheading with formatting, colors, and fonts.
     */
    richSubheading?: string | null;
    draftData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    publishedData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    status?: ('draft' | 'published') | null;
    /**
     * Add, remove, or reorder social media links
     */
    socialLinks?:
      | {
          platform: string;
          url: string;
          icon?: string | null;
          color?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-settings".
 */
export interface HeroSetting {
  id: number;
  headlineLine1: {
    text: string;
    color?: string | null;
    font?: ('font-display' | 'font-sans' | 'font-mono') | null;
  };
  headlineAccent: {
    text: string;
    color?: string | null;
    font?: ('font-display' | 'font-sans' | 'font-mono') | null;
  };
  headlineLine2: {
    text: string;
    color?: string | null;
    font?: ('font-display' | 'font-sans' | 'font-mono') | null;
  };
  subtitle: {
    text: string;
    color?: string | null;
    font?: ('font-display' | 'font-sans' | 'font-mono') | null;
  };
  subtitleBold: {
    text: string;
    color?: string | null;
    font?: ('font-display' | 'font-sans' | 'font-mono') | null;
  };
  ctaPrimaryText?: string | null;
  ctaSecondaryText?: string | null;
  ctaPrimaryColor?: string | null;
  badges?:
    | {
        text: string;
        /**
         * Badge icon
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  responseLabel: {
    text: string;
    color?: string | null;
    font?: ('font-display' | 'font-sans' | 'font-mono') | null;
  };
  categoryLinks?:
    | {
        label: string;
        /**
         * Category icon
         */
        icon?: string | null;
        color?: string | null;
        /**
         * Link target (e.g. #residential)
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Business name, contact info, hours & SEO defaults — these appear across the entire website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Your business name
   */
  businessName?: string | null;
  /**
   * Tagline shown in the header
   */
  tagline?: string | null;
  /**
   * Business logo
   */
  logo?: (number | null) | Media;
  /**
   * Average response time (e.g. "20-30 min")
   */
  responseTime?: string | null;
  /**
   * Main phone number
   */
  phone?: string | null;
  /**
   * Contact email
   */
  email?: string | null;
  /**
   * Business address
   */
  address?: {
    /**
     * Street address
     */
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  /**
   * Business hours — add one row per schedule
   */
  hours?:
    | {
        /**
         * e.g. Monday-Friday, Weekends
         */
        day?: string | null;
        /**
         * e.g. 24/7, 8am-6pm
         */
        hours?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Default page title for search engines
   */
  defaultSeoTitle?: string | null;
  /**
   * Default meta description (150-160 chars ideal)
   */
  defaultSeoDescription?: string | null;
  /**
   * Google Analytics tracking ID (e.g. G-XXXXXXXXXX)
   */
  analyticsId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Drag and reorder the sections on your homepage. Toggle sections on/off, edit headings & subheadings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-layout".
 */
export interface HomepageLayout {
  id: number;
  /**
   * ↕️ Drag rows to reorder sections on the homepage
   */
  sections?:
    | {
        /**
         * Which section to display
         */
        sectionType:
          | 'hero'
          | 'services'
          | 'reviews'
          | 'gallery'
          | 'quote'
          | 'vehicle-verifier'
          | 'team'
          | 'map'
          | 'faq'
          | 'contact'
          | 'visitor-counter';
        /**
         * Section heading (optional override)
         */
        heading?: string | null;
        /**
         * Section subheading (optional override)
         */
        subheading?: string | null;
        /**
         * ✅ Show this section
         */
        isActive?: boolean | null;
        /**
         * Auto-updated on save (drag to reorder)
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Menu links shown in the website header — drag to reorder, toggle to show/hide
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * ↕️ Drag rows to reorder menu items
   */
  items?:
    | {
        /**
         * Menu text (e.g. Services)
         */
        label: string;
        /**
         * Link target (e.g. #services)
         */
        href: string;
        /**
         * Visible
         */
        isActive?: boolean | null;
        /**
         * Auto-updated on save
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure WAHA (self-hosted WhatsApp) to receive instant notifications when a new quote request comes in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-settings".
 */
export interface WhatsappSetting {
  id: number;
  /**
   * When checked, a WhatsApp message is sent to the business number on every new quote request.
   */
  enabled?: boolean | null;
  /**
   * Base URL of your WAHA Docker container, e.g. http://localhost:3002
   */
  wahaUrl?: string | null;
  /**
   * WAHA session name — leave as "default" unless you created a custom one.
   */
  wahaSession?: string | null;
  /**
   * Only required if you secured WAHA with an API key.
   */
  wahaApiKey?: string | null;
  /**
   * International format, digits only — no +, spaces or dashes. e.g. 12165551234
   */
  businessPhone?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections-settings_select".
 */
export interface SectionsSettingsSelect<T extends boolean = true> {
  _sectionSelector?: T;
  services?:
    | T
    | {
        heading?: T;
        richHeading?: T;
        headingAccent?: T;
        richAccent?: T;
        description?: T;
        richDescription?: T;
      };
  residential?:
    | T
    | {
        label?: T;
        description?: T;
        color?: T;
        icon?: T;
      };
  commercial?:
    | T
    | {
        label?: T;
        description?: T;
        color?: T;
        icon?: T;
      };
  automotive?:
    | T
    | {
        label?: T;
        description?: T;
        color?: T;
        icon?: T;
      };
  reviews?:
    | T
    | {
        heading?: T;
        richHeading?: T;
        subheading?: T;
        richSubheading?: T;
        draftData?: T;
        publishedData?: T;
        status?: T;
      };
  gallery?:
    | T
    | {
        heading?: T;
        richHeading?: T;
        subheading?: T;
        richSubheading?: T;
        draftData?: T;
        publishedData?: T;
        status?: T;
      };
  quote?:
    | T
    | {
        heading?: T;
        richHeading?: T;
        subheading?: T;
        richSubheading?: T;
        draftData?: T;
        publishedData?: T;
        status?: T;
      };
  vehicleVerifier?:
    | T
    | {
        heading?: T;
        richHeading?: T;
        subheading?: T;
        richSubheading?: T;
        draftData?: T;
        publishedData?: T;
        status?: T;
      };
  team?:
    | T
    | {
        heading?: T;
        richHeading?: T;
        subheading?: T;
        richSubheading?: T;
        draftData?: T;
        publishedData?: T;
        status?: T;
      };
  serviceArea?:
    | T
    | {
        heading?: T;
        richHeading?: T;
        subheading?: T;
        richSubheading?: T;
        draftData?: T;
        publishedData?: T;
        status?: T;
      };
  faq?:
    | T
    | {
        heading?: T;
        richHeading?: T;
        subheading?: T;
        richSubheading?: T;
        draftData?: T;
        publishedData?: T;
        status?: T;
      };
  contact?:
    | T
    | {
        heading?: T;
        richHeading?: T;
        subheading?: T;
        richSubheading?: T;
        draftData?: T;
        publishedData?: T;
        status?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              icon?: T;
              color?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-settings_select".
 */
export interface HeroSettingsSelect<T extends boolean = true> {
  headlineLine1?:
    | T
    | {
        text?: T;
        color?: T;
        font?: T;
      };
  headlineAccent?:
    | T
    | {
        text?: T;
        color?: T;
        font?: T;
      };
  headlineLine2?:
    | T
    | {
        text?: T;
        color?: T;
        font?: T;
      };
  subtitle?:
    | T
    | {
        text?: T;
        color?: T;
        font?: T;
      };
  subtitleBold?:
    | T
    | {
        text?: T;
        color?: T;
        font?: T;
      };
  ctaPrimaryText?: T;
  ctaSecondaryText?: T;
  ctaPrimaryColor?: T;
  badges?:
    | T
    | {
        text?: T;
        icon?: T;
        id?: T;
      };
  responseLabel?:
    | T
    | {
        text?: T;
        color?: T;
        font?: T;
      };
  categoryLinks?:
    | T
    | {
        label?: T;
        icon?: T;
        color?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessName?: T;
  tagline?: T;
  logo?: T;
  responseTime?: T;
  phone?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  hours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  defaultSeoTitle?: T;
  defaultSeoDescription?: T;
  analyticsId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-layout_select".
 */
export interface HomepageLayoutSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        sectionType?: T;
        heading?: T;
        subheading?: T;
        isActive?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        isActive?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-settings_select".
 */
export interface WhatsappSettingsSelect<T extends boolean = true> {
  enabled?: T;
  wahaUrl?: T;
  wahaSession?: T;
  wahaApiKey?: T;
  businessPhone?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}